"""users table

Revision ID: 86d698daf709
Revises: 
Create Date: 2021-01-09 16:19:52.325101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d698daf709'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('contact', sa.String(length=128), nullable=True),
    sa.Column('age', sa.String(length=128), nullable=True),
    sa.Column('recent_company', sa.String(length=128), nullable=True),
    sa.Column('role_in_company', sa.String(length=128), nullable=True),
    sa.Column('current_ctc', sa.String(length=128), nullable=True),
    sa.Column('fixed_component_ctc', sa.String(length=128), nullable=True),
    sa.Column('experience', sa.String(length=128), nullable=True),
    sa.Column('comfort', sa.String(length=128), nullable=True),
    sa.Column('relocate', sa.String(length=128), nullable=True),
    sa.Column('rate_english', sa.String(length=128), nullable=True),
    sa.Column('skills', sa.String(length=128), nullable=True),
    sa.Column('industries', sa.String(length=128), nullable=True),
    sa.Column('profile', sa.String(length=128), nullable=True),
    sa.Column('factors', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_timestamp'), 'user', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_timestamp'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
